# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from grpc_svc.pb.tutor.v1 import tutor_pb2 as tutor_dot_v1_dot_tutor__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tutor/v1/tutor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TutorServiceStub:
    """TutorService is implemented by adaptive-learning-repetitor.
    Anki is the gRPC client.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/tutor.v1.TutorService/Health',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=tutor_dot_v1_dot_tutor__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.EnsureSession = channel.unary_unary(
                '/tutor.v1.TutorService/EnsureSession',
                request_serializer=tutor_dot_v1_dot_tutor__pb2.EnsureSessionRequest.SerializeToString,
                response_deserializer=tutor_dot_v1_dot_tutor__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.Chat = channel.unary_stream(
                '/tutor.v1.TutorService/Chat',
                request_serializer=tutor_dot_v1_dot_tutor__pb2.ChatRequest.SerializeToString,
                response_deserializer=tutor_dot_v1_dot_tutor__pb2.ChatEvent.FromString,
                _registered_method=True)
        self.GeneratePractice = channel.unary_unary(
                '/tutor.v1.TutorService/GeneratePractice',
                request_serializer=tutor_dot_v1_dot_tutor__pb2.PracticeRequest.SerializeToString,
                response_deserializer=tutor_dot_v1_dot_tutor__pb2.PracticeResponse.FromString,
                _registered_method=True)
        self.SearchRag = channel.unary_unary(
                '/tutor.v1.TutorService/SearchRag',
                request_serializer=tutor_dot_v1_dot_tutor__pb2.RagSearchRequest.SerializeToString,
                response_deserializer=tutor_dot_v1_dot_tutor__pb2.RagSearchResponse.FromString,
                _registered_method=True)
        self.EnrichWord = channel.unary_unary(
                '/tutor.v1.TutorService/EnrichWord',
                request_serializer=tutor_dot_v1_dot_tutor__pb2.EnrichWordRequest.SerializeToString,
                response_deserializer=tutor_dot_v1_dot_tutor__pb2.EnrichWordResponse.FromString,
                _registered_method=True)
        self.PublishEvent = channel.unary_unary(
                '/tutor.v1.TutorService/PublishEvent',
                request_serializer=tutor_dot_v1_dot_tutor__pb2.PublishEventRequest.SerializeToString,
                response_deserializer=tutor_dot_v1_dot_tutor__pb2.PublishEventResponse.FromString,
                _registered_method=True)
        self.ExplainError = channel.unary_unary(
                '/tutor.v1.TutorService/ExplainError',
                request_serializer=tutor_dot_v1_dot_tutor__pb2.ExplainErrorRequest.SerializeToString,
                response_deserializer=tutor_dot_v1_dot_tutor__pb2.ExplainErrorResponse.FromString,
                _registered_method=True)
        self.GetWeakTopics = channel.unary_unary(
                '/tutor.v1.TutorService/GetWeakTopics',
                request_serializer=tutor_dot_v1_dot_tutor__pb2.GetWeakTopicsRequest.SerializeToString,
                response_deserializer=tutor_dot_v1_dot_tutor__pb2.GetWeakTopicsResponse.FromString,
                _registered_method=True)


class TutorServiceServicer:
    """TutorService is implemented by adaptive-learning-repetitor.
    Anki is the gRPC client.
    """

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnsureSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GeneratePractice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchRag(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnrichWord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExplainError(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWeakTopics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TutorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=tutor_dot_v1_dot_tutor__pb2.StatusResponse.SerializeToString,
            ),
            'EnsureSession': grpc.unary_unary_rpc_method_handler(
                    servicer.EnsureSession,
                    request_deserializer=tutor_dot_v1_dot_tutor__pb2.EnsureSessionRequest.FromString,
                    response_serializer=tutor_dot_v1_dot_tutor__pb2.StatusResponse.SerializeToString,
            ),
            'Chat': grpc.unary_stream_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=tutor_dot_v1_dot_tutor__pb2.ChatRequest.FromString,
                    response_serializer=tutor_dot_v1_dot_tutor__pb2.ChatEvent.SerializeToString,
            ),
            'GeneratePractice': grpc.unary_unary_rpc_method_handler(
                    servicer.GeneratePractice,
                    request_deserializer=tutor_dot_v1_dot_tutor__pb2.PracticeRequest.FromString,
                    response_serializer=tutor_dot_v1_dot_tutor__pb2.PracticeResponse.SerializeToString,
            ),
            'SearchRag': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchRag,
                    request_deserializer=tutor_dot_v1_dot_tutor__pb2.RagSearchRequest.FromString,
                    response_serializer=tutor_dot_v1_dot_tutor__pb2.RagSearchResponse.SerializeToString,
            ),
            'EnrichWord': grpc.unary_unary_rpc_method_handler(
                    servicer.EnrichWord,
                    request_deserializer=tutor_dot_v1_dot_tutor__pb2.EnrichWordRequest.FromString,
                    response_serializer=tutor_dot_v1_dot_tutor__pb2.EnrichWordResponse.SerializeToString,
            ),
            'PublishEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishEvent,
                    request_deserializer=tutor_dot_v1_dot_tutor__pb2.PublishEventRequest.FromString,
                    response_serializer=tutor_dot_v1_dot_tutor__pb2.PublishEventResponse.SerializeToString,
            ),
            'ExplainError': grpc.unary_unary_rpc_method_handler(
                    servicer.ExplainError,
                    request_deserializer=tutor_dot_v1_dot_tutor__pb2.ExplainErrorRequest.FromString,
                    response_serializer=tutor_dot_v1_dot_tutor__pb2.ExplainErrorResponse.SerializeToString,
            ),
            'GetWeakTopics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWeakTopics,
                    request_deserializer=tutor_dot_v1_dot_tutor__pb2.GetWeakTopicsRequest.FromString,
                    response_serializer=tutor_dot_v1_dot_tutor__pb2.GetWeakTopicsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tutor.v1.TutorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tutor.v1.TutorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TutorService:
    """TutorService is implemented by adaptive-learning-repetitor.
    Anki is the gRPC client.
    """

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tutor.v1.TutorService/Health',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            tutor_dot_v1_dot_tutor__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnsureSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tutor.v1.TutorService/EnsureSession',
            tutor_dot_v1_dot_tutor__pb2.EnsureSessionRequest.SerializeToString,
            tutor_dot_v1_dot_tutor__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tutor.v1.TutorService/Chat',
            tutor_dot_v1_dot_tutor__pb2.ChatRequest.SerializeToString,
            tutor_dot_v1_dot_tutor__pb2.ChatEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GeneratePractice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tutor.v1.TutorService/GeneratePractice',
            tutor_dot_v1_dot_tutor__pb2.PracticeRequest.SerializeToString,
            tutor_dot_v1_dot_tutor__pb2.PracticeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchRag(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tutor.v1.TutorService/SearchRag',
            tutor_dot_v1_dot_tutor__pb2.RagSearchRequest.SerializeToString,
            tutor_dot_v1_dot_tutor__pb2.RagSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnrichWord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tutor.v1.TutorService/EnrichWord',
            tutor_dot_v1_dot_tutor__pb2.EnrichWordRequest.SerializeToString,
            tutor_dot_v1_dot_tutor__pb2.EnrichWordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tutor.v1.TutorService/PublishEvent',
            tutor_dot_v1_dot_tutor__pb2.PublishEventRequest.SerializeToString,
            tutor_dot_v1_dot_tutor__pb2.PublishEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExplainError(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tutor.v1.TutorService/ExplainError',
            tutor_dot_v1_dot_tutor__pb2.ExplainErrorRequest.SerializeToString,
            tutor_dot_v1_dot_tutor__pb2.ExplainErrorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWeakTopics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tutor.v1.TutorService/GetWeakTopics',
            tutor_dot_v1_dot_tutor__pb2.GetWeakTopicsRequest.SerializeToString,
            tutor_dot_v1_dot_tutor__pb2.GetWeakTopicsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
