// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: tutor/v1/tutor.proto

package tutorpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TutorService_Health_FullMethodName           = "/tutor.v1.TutorService/Health"
	TutorService_EnsureSession_FullMethodName    = "/tutor.v1.TutorService/EnsureSession"
	TutorService_Chat_FullMethodName             = "/tutor.v1.TutorService/Chat"
	TutorService_GeneratePractice_FullMethodName = "/tutor.v1.TutorService/GeneratePractice"
	TutorService_SearchRag_FullMethodName        = "/tutor.v1.TutorService/SearchRag"
	TutorService_EnrichWord_FullMethodName       = "/tutor.v1.TutorService/EnrichWord"
	TutorService_PublishEvent_FullMethodName     = "/tutor.v1.TutorService/PublishEvent"
	TutorService_ExplainError_FullMethodName     = "/tutor.v1.TutorService/ExplainError"
	TutorService_GetWeakTopics_FullMethodName    = "/tutor.v1.TutorService/GetWeakTopics"
)

// TutorServiceClient is the client API for TutorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TutorService is implemented by adaptive-learning-repetitor.
// Anki is the gRPC client.
type TutorServiceClient interface {
	Health(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*StatusResponse, error)
	EnsureSession(ctx context.Context, in *EnsureSessionRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatEvent], error)
	GeneratePractice(ctx context.Context, in *PracticeRequest, opts ...grpc.CallOption) (*PracticeResponse, error)
	SearchRag(ctx context.Context, in *RagSearchRequest, opts ...grpc.CallOption) (*RagSearchResponse, error)
	EnrichWord(ctx context.Context, in *EnrichWordRequest, opts ...grpc.CallOption) (*EnrichWordResponse, error)
	PublishEvent(ctx context.Context, in *PublishEventRequest, opts ...grpc.CallOption) (*PublishEventResponse, error)
	ExplainError(ctx context.Context, in *ExplainErrorRequest, opts ...grpc.CallOption) (*ExplainErrorResponse, error)
	GetWeakTopics(ctx context.Context, in *GetWeakTopicsRequest, opts ...grpc.CallOption) (*GetWeakTopicsResponse, error)
}

type tutorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTutorServiceClient(cc grpc.ClientConnInterface) TutorServiceClient {
	return &tutorServiceClient{cc}
}

func (c *tutorServiceClient) Health(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, TutorService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tutorServiceClient) EnsureSession(ctx context.Context, in *EnsureSessionRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, TutorService_EnsureSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tutorServiceClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TutorService_ServiceDesc.Streams[0], TutorService_Chat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatRequest, ChatEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TutorService_ChatClient = grpc.ServerStreamingClient[ChatEvent]

func (c *tutorServiceClient) GeneratePractice(ctx context.Context, in *PracticeRequest, opts ...grpc.CallOption) (*PracticeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PracticeResponse)
	err := c.cc.Invoke(ctx, TutorService_GeneratePractice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tutorServiceClient) SearchRag(ctx context.Context, in *RagSearchRequest, opts ...grpc.CallOption) (*RagSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RagSearchResponse)
	err := c.cc.Invoke(ctx, TutorService_SearchRag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tutorServiceClient) EnrichWord(ctx context.Context, in *EnrichWordRequest, opts ...grpc.CallOption) (*EnrichWordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrichWordResponse)
	err := c.cc.Invoke(ctx, TutorService_EnrichWord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tutorServiceClient) PublishEvent(ctx context.Context, in *PublishEventRequest, opts ...grpc.CallOption) (*PublishEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishEventResponse)
	err := c.cc.Invoke(ctx, TutorService_PublishEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tutorServiceClient) ExplainError(ctx context.Context, in *ExplainErrorRequest, opts ...grpc.CallOption) (*ExplainErrorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExplainErrorResponse)
	err := c.cc.Invoke(ctx, TutorService_ExplainError_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tutorServiceClient) GetWeakTopics(ctx context.Context, in *GetWeakTopicsRequest, opts ...grpc.CallOption) (*GetWeakTopicsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWeakTopicsResponse)
	err := c.cc.Invoke(ctx, TutorService_GetWeakTopics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TutorServiceServer is the server API for TutorService service.
// All implementations must embed UnimplementedTutorServiceServer
// for forward compatibility.
//
// TutorService is implemented by adaptive-learning-repetitor.
// Anki is the gRPC client.
type TutorServiceServer interface {
	Health(context.Context, *emptypb.Empty) (*StatusResponse, error)
	EnsureSession(context.Context, *EnsureSessionRequest) (*StatusResponse, error)
	Chat(*ChatRequest, grpc.ServerStreamingServer[ChatEvent]) error
	GeneratePractice(context.Context, *PracticeRequest) (*PracticeResponse, error)
	SearchRag(context.Context, *RagSearchRequest) (*RagSearchResponse, error)
	EnrichWord(context.Context, *EnrichWordRequest) (*EnrichWordResponse, error)
	PublishEvent(context.Context, *PublishEventRequest) (*PublishEventResponse, error)
	ExplainError(context.Context, *ExplainErrorRequest) (*ExplainErrorResponse, error)
	GetWeakTopics(context.Context, *GetWeakTopicsRequest) (*GetWeakTopicsResponse, error)
	mustEmbedUnimplementedTutorServiceServer()
}

// UnimplementedTutorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTutorServiceServer struct{}

func (UnimplementedTutorServiceServer) Health(context.Context, *emptypb.Empty) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedTutorServiceServer) EnsureSession(context.Context, *EnsureSessionRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnsureSession not implemented")
}
func (UnimplementedTutorServiceServer) Chat(*ChatRequest, grpc.ServerStreamingServer[ChatEvent]) error {
	return status.Error(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedTutorServiceServer) GeneratePractice(context.Context, *PracticeRequest) (*PracticeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GeneratePractice not implemented")
}
func (UnimplementedTutorServiceServer) SearchRag(context.Context, *RagSearchRequest) (*RagSearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchRag not implemented")
}
func (UnimplementedTutorServiceServer) EnrichWord(context.Context, *EnrichWordRequest) (*EnrichWordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnrichWord not implemented")
}
func (UnimplementedTutorServiceServer) PublishEvent(context.Context, *PublishEventRequest) (*PublishEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishEvent not implemented")
}
func (UnimplementedTutorServiceServer) ExplainError(context.Context, *ExplainErrorRequest) (*ExplainErrorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExplainError not implemented")
}
func (UnimplementedTutorServiceServer) GetWeakTopics(context.Context, *GetWeakTopicsRequest) (*GetWeakTopicsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWeakTopics not implemented")
}
func (UnimplementedTutorServiceServer) mustEmbedUnimplementedTutorServiceServer() {}
func (UnimplementedTutorServiceServer) testEmbeddedByValue()                      {}

// UnsafeTutorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TutorServiceServer will
// result in compilation errors.
type UnsafeTutorServiceServer interface {
	mustEmbedUnimplementedTutorServiceServer()
}

func RegisterTutorServiceServer(s grpc.ServiceRegistrar, srv TutorServiceServer) {
	// If the following call panics, it indicates UnimplementedTutorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TutorService_ServiceDesc, srv)
}

func _TutorService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TutorServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TutorService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TutorServiceServer).Health(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TutorService_EnsureSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnsureSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TutorServiceServer).EnsureSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TutorService_EnsureSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TutorServiceServer).EnsureSession(ctx, req.(*EnsureSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TutorService_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TutorServiceServer).Chat(m, &grpc.GenericServerStream[ChatRequest, ChatEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TutorService_ChatServer = grpc.ServerStreamingServer[ChatEvent]

func _TutorService_GeneratePractice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PracticeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TutorServiceServer).GeneratePractice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TutorService_GeneratePractice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TutorServiceServer).GeneratePractice(ctx, req.(*PracticeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TutorService_SearchRag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RagSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TutorServiceServer).SearchRag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TutorService_SearchRag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TutorServiceServer).SearchRag(ctx, req.(*RagSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TutorService_EnrichWord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrichWordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TutorServiceServer).EnrichWord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TutorService_EnrichWord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TutorServiceServer).EnrichWord(ctx, req.(*EnrichWordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TutorService_PublishEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TutorServiceServer).PublishEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TutorService_PublishEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TutorServiceServer).PublishEvent(ctx, req.(*PublishEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TutorService_ExplainError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExplainErrorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TutorServiceServer).ExplainError(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TutorService_ExplainError_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TutorServiceServer).ExplainError(ctx, req.(*ExplainErrorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TutorService_GetWeakTopics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWeakTopicsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TutorServiceServer).GetWeakTopics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TutorService_GetWeakTopics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TutorServiceServer).GetWeakTopics(ctx, req.(*GetWeakTopicsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TutorService_ServiceDesc is the grpc.ServiceDesc for TutorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TutorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tutor.v1.TutorService",
	HandlerType: (*TutorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _TutorService_Health_Handler,
		},
		{
			MethodName: "EnsureSession",
			Handler:    _TutorService_EnsureSession_Handler,
		},
		{
			MethodName: "GeneratePractice",
			Handler:    _TutorService_GeneratePractice_Handler,
		},
		{
			MethodName: "SearchRag",
			Handler:    _TutorService_SearchRag_Handler,
		},
		{
			MethodName: "EnrichWord",
			Handler:    _TutorService_EnrichWord_Handler,
		},
		{
			MethodName: "PublishEvent",
			Handler:    _TutorService_PublishEvent_Handler,
		},
		{
			MethodName: "ExplainError",
			Handler:    _TutorService_ExplainError_Handler,
		},
		{
			MethodName: "GetWeakTopics",
			Handler:    _TutorService_GetWeakTopics_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Chat",
			Handler:       _TutorService_Chat_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "tutor/v1/tutor.proto",
}
