// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: tutor/v1/tutor.proto

package tutorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RagCorpus int32

const (
	RagCorpus_RAG_CORPUS_UNSPECIFIED RagCorpus = 0
	RagCorpus_RAG_CORPUS_EXERCISE    RagCorpus = 1
	RagCorpus_RAG_CORPUS_EXAMPLE     RagCorpus = 2
	RagCorpus_RAG_CORPUS_EXPLANATION RagCorpus = 3
)

// Enum value maps for RagCorpus.
var (
	RagCorpus_name = map[int32]string{
		0: "RAG_CORPUS_UNSPECIFIED",
		1: "RAG_CORPUS_EXERCISE",
		2: "RAG_CORPUS_EXAMPLE",
		3: "RAG_CORPUS_EXPLANATION",
	}
	RagCorpus_value = map[string]int32{
		"RAG_CORPUS_UNSPECIFIED": 0,
		"RAG_CORPUS_EXERCISE":    1,
		"RAG_CORPUS_EXAMPLE":     2,
		"RAG_CORPUS_EXPLANATION": 3,
	}
)

func (x RagCorpus) Enum() *RagCorpus {
	p := new(RagCorpus)
	*p = x
	return p
}

func (x RagCorpus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RagCorpus) Descriptor() protoreflect.EnumDescriptor {
	return file_tutor_v1_tutor_proto_enumTypes[0].Descriptor()
}

func (RagCorpus) Type() protoreflect.EnumType {
	return &file_tutor_v1_tutor_proto_enumTypes[0]
}

func (x RagCorpus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RagCorpus.Descriptor instead.
func (RagCorpus) EnumDescriptor() ([]byte, []int) {
	return file_tutor_v1_tutor_proto_rawDescGZIP(), []int{0}
}

// Credentials for service-to-service auth against repetitor user store.
type Credentials struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Credentials) Reset() {
	*x = Credentials{}
	mi := &file_tutor_v1_tutor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credentials) ProtoMessage() {}

func (x *Credentials) ProtoReflect() protoreflect.Message {
	mi := &file_tutor_v1_tutor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credentials.ProtoReflect.Descriptor instead.
func (*Credentials) Descriptor() ([]byte, []int) {
	return file_tutor_v1_tutor_proto_rawDescGZIP(), []int{0}
}

func (x *Credentials) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Credentials) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// Resolved session: user + project + chat ids.
type Session struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Credentials    *Credentials           `protobuf:"bytes,1,opt,name=credentials,proto3" json:"credentials,omitempty"`
	ProjectId      string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ChatId         string                 `protobuf:"bytes,3,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	PracticeChatId string                 `protobuf:"bytes,4,opt,name=practice_chat_id,json=practiceChatId,proto3" json:"practice_chat_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_tutor_v1_tutor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_tutor_v1_tutor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_tutor_v1_tutor_proto_rawDescGZIP(), []int{1}
}

func (x *Session) GetCredentials() *Credentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *Session) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Session) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *Session) GetPracticeChatId() string {
	if x != nil {
		return x.PracticeChatId
	}
	return ""
}

type EnsureSessionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Credentials    *Credentials           `protobuf:"bytes,1,opt,name=credentials,proto3" json:"credentials,omitempty"`
	ProjectId      string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ChatId         string                 `protobuf:"bytes,3,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	PracticeChatId string                 `protobuf:"bytes,4,opt,name=practice_chat_id,json=practiceChatId,proto3" json:"practice_chat_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EnsureSessionRequest) Reset() {
	*x = EnsureSessionRequest{}
	mi := &file_tutor_v1_tutor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureSessionRequest) ProtoMessage() {}

func (x *EnsureSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tutor_v1_tutor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureSessionRequest.ProtoReflect.Descriptor instead.
func (*EnsureSessionRequest) Descriptor() ([]byte, []int) {
	return file_tutor_v1_tutor_proto_rawDescGZIP(), []int{2}
}

func (x *EnsureSessionRequest) GetCredentials() *Credentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *EnsureSessionRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *EnsureSessionRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *EnsureSessionRequest) GetPracticeChatId() string {
	if x != nil {
		return x.PracticeChatId
	}
	return ""
}

type StatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ready          bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	Address        string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	ProjectId      string                 `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ChatId         string                 `protobuf:"bytes,4,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	PracticeChatId string                 `protobuf:"bytes,5,opt,name=practice_chat_id,json=practiceChatId,proto3" json:"practice_chat_id,omitempty"`
	Error          string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_tutor_v1_tutor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tutor_v1_tutor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_tutor_v1_tutor_proto_rawDescGZIP(), []int{3}
}

func (x *StatusResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *StatusResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *StatusResponse) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *StatusResponse) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *StatusResponse) GetPracticeChatId() string {
	if x != nil {
		return x.PracticeChatId
	}
	return ""
}

func (x *StatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ChatRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Session         *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	UsePracticeChat bool                   `protobuf:"varint,3,opt,name=use_practice_chat,json=usePracticeChat,proto3" json:"use_practice_chat,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_tutor_v1_tutor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tutor_v1_tutor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_tutor_v1_tutor_proto_rawDescGZIP(), []int{4}
}

func (x *ChatRequest) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *ChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatRequest) GetUsePracticeChat() bool {
	if x != nil {
		return x.UsePracticeChat
	}
	return false
}

type ChatEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // content | status | error | done
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatEvent) Reset() {
	*x = ChatEvent{}
	mi := &file_tutor_v1_tutor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatEvent) ProtoMessage() {}

func (x *ChatEvent) ProtoReflect() protoreflect.Message {
	mi := &file_tutor_v1_tutor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatEvent.ProtoReflect.Descriptor instead.
func (*ChatEvent) Descriptor() ([]byte, []int) {
	return file_tutor_v1_tutor_proto_rawDescGZIP(), []int{5}
}

func (x *ChatEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ChatEvent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ChatEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PracticeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Words         []string               `protobuf:"bytes,2,rep,name=words,proto3" json:"words,omitempty"`
	Level         string                 `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PracticeRequest) Reset() {
	*x = PracticeRequest{}
	mi := &file_tutor_v1_tutor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PracticeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PracticeRequest) ProtoMessage() {}

func (x *PracticeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tutor_v1_tutor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PracticeRequest.ProtoReflect.Descriptor instead.
func (*PracticeRequest) Descriptor() ([]byte, []int) {
	return file_tutor_v1_tutor_proto_rawDescGZIP(), []int{6}
}

func (x *PracticeRequest) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *PracticeRequest) GetWords() []string {
	if x != nil {
		return x.Words
	}
	return nil
}

func (x *PracticeRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

type PracticeQuestion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Options       []string               `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
	CorrectIndex  int32                  `protobuf:"varint,3,opt,name=correct_index,json=correctIndex,proto3" json:"correct_index,omitempty"`
	Explanation   string                 `protobuf:"bytes,4,opt,name=explanation,proto3" json:"explanation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PracticeQuestion) Reset() {
	*x = PracticeQuestion{}
	mi := &file_tutor_v1_tutor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PracticeQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PracticeQuestion) ProtoMessage() {}

func (x *PracticeQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_tutor_v1_tutor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PracticeQuestion.ProtoReflect.Descriptor instead.
func (*PracticeQuestion) Descriptor() ([]byte, []int) {
	return file_tutor_v1_tutor_proto_rawDescGZIP(), []int{7}
}

func (x *PracticeQuestion) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *PracticeQuestion) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *PracticeQuestion) GetCorrectIndex() int32 {
	if x != nil {
		return x.CorrectIndex
	}
	return 0
}

func (x *PracticeQuestion) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

type PracticeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Questions     []*PracticeQuestion    `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	RagSources    []string               `protobuf:"bytes,3,rep,name=rag_sources,json=ragSources,proto3" json:"rag_sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PracticeResponse) Reset() {
	*x = PracticeResponse{}
	mi := &file_tutor_v1_tutor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PracticeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PracticeResponse) ProtoMessage() {}

func (x *PracticeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tutor_v1_tutor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PracticeResponse.ProtoReflect.Descriptor instead.
func (*PracticeResponse) Descriptor() ([]byte, []int) {
	return file_tutor_v1_tutor_proto_rawDescGZIP(), []int{8}
}

func (x *PracticeResponse) GetQuestions() []*PracticeQuestion {
	if x != nil {
		return x.Questions
	}
	return nil
}

func (x *PracticeResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *PracticeResponse) GetRagSources() []string {
	if x != nil {
		return x.RagSources
	}
	return nil
}

type RagSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Corpus        RagCorpus              `protobuf:"varint,3,opt,name=corpus,proto3,enum=tutor.v1.RagCorpus" json:"corpus,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RagSearchRequest) Reset() {
	*x = RagSearchRequest{}
	mi := &file_tutor_v1_tutor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RagSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RagSearchRequest) ProtoMessage() {}

func (x *RagSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tutor_v1_tutor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RagSearchRequest.ProtoReflect.Descriptor instead.
func (*RagSearchRequest) Descriptor() ([]byte, []int) {
	return file_tutor_v1_tutor_proto_rawDescGZIP(), []int{9}
}

func (x *RagSearchRequest) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *RagSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RagSearchRequest) GetCorpus() RagCorpus {
	if x != nil {
		return x.Corpus
	}
	return RagCorpus_RAG_CORPUS_UNSPECIFIED
}

func (x *RagSearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type RagChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Snippet       string                 `protobuf:"bytes,3,opt,name=snippet,proto3" json:"snippet,omitempty"`
	Score         float32                `protobuf:"fixed32,4,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RagChunk) Reset() {
	*x = RagChunk{}
	mi := &file_tutor_v1_tutor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RagChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RagChunk) ProtoMessage() {}

func (x *RagChunk) ProtoReflect() protoreflect.Message {
	mi := &file_tutor_v1_tutor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RagChunk.ProtoReflect.Descriptor instead.
func (*RagChunk) Descriptor() ([]byte, []int) {
	return file_tutor_v1_tutor_proto_rawDescGZIP(), []int{10}
}

func (x *RagChunk) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RagChunk) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RagChunk) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

func (x *RagChunk) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type RagSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunks        []*RagChunk            `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"`
	Context       string                 `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RagSearchResponse) Reset() {
	*x = RagSearchResponse{}
	mi := &file_tutor_v1_tutor_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RagSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RagSearchResponse) ProtoMessage() {}

func (x *RagSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tutor_v1_tutor_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RagSearchResponse.ProtoReflect.Descriptor instead.
func (*RagSearchResponse) Descriptor() ([]byte, []int) {
	return file_tutor_v1_tutor_proto_rawDescGZIP(), []int{11}
}

func (x *RagSearchResponse) GetChunks() []*RagChunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *RagSearchResponse) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

type EnrichWordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Word          string                 `protobuf:"bytes,2,opt,name=word,proto3" json:"word,omitempty"`
	Level         string                 `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichWordRequest) Reset() {
	*x = EnrichWordRequest{}
	mi := &file_tutor_v1_tutor_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichWordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichWordRequest) ProtoMessage() {}

func (x *EnrichWordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tutor_v1_tutor_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichWordRequest.ProtoReflect.Descriptor instead.
func (*EnrichWordRequest) Descriptor() ([]byte, []int) {
	return file_tutor_v1_tutor_proto_rawDescGZIP(), []int{12}
}

func (x *EnrichWordRequest) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *EnrichWordRequest) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *EnrichWordRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

type EnrichWordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Translation   string                 `protobuf:"bytes,1,opt,name=translation,proto3" json:"translation,omitempty"`
	Example       string                 `protobuf:"bytes,2,opt,name=example,proto3" json:"example,omitempty"`
	Transcription string                 `protobuf:"bytes,3,opt,name=transcription,proto3" json:"transcription,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"` // rag | llm
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichWordResponse) Reset() {
	*x = EnrichWordResponse{}
	mi := &file_tutor_v1_tutor_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichWordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichWordResponse) ProtoMessage() {}

func (x *EnrichWordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tutor_v1_tutor_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichWordResponse.ProtoReflect.Descriptor instead.
func (*EnrichWordResponse) Descriptor() ([]byte, []int) {
	return file_tutor_v1_tutor_proto_rawDescGZIP(), []int{13}
}

func (x *EnrichWordResponse) GetTranslation() string {
	if x != nil {
		return x.Translation
	}
	return ""
}

func (x *EnrichWordResponse) GetExample() string {
	if x != nil {
		return x.Example
	}
	return ""
}

func (x *EnrichWordResponse) GetTranscription() string {
	if x != nil {
		return x.Transcription
	}
	return ""
}

func (x *EnrichWordResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type PublishEventRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Session        *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Word           string                 `protobuf:"bytes,2,opt,name=word,proto3" json:"word,omitempty"`
	Correct        bool                   `protobuf:"varint,3,opt,name=correct,proto3" json:"correct,omitempty"`
	ResponseTimeMs int32                  `protobuf:"varint,4,opt,name=response_time_ms,json=responseTimeMs,proto3" json:"response_time_ms,omitempty"`
	Attempts       int32                  `protobuf:"varint,5,opt,name=attempts,proto3" json:"attempts,omitempty"`
	CardType       string                 `protobuf:"bytes,6,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`
	Difficulty     string                 `protobuf:"bytes,7,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PublishEventRequest) Reset() {
	*x = PublishEventRequest{}
	mi := &file_tutor_v1_tutor_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishEventRequest) ProtoMessage() {}

func (x *PublishEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tutor_v1_tutor_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishEventRequest.ProtoReflect.Descriptor instead.
func (*PublishEventRequest) Descriptor() ([]byte, []int) {
	return file_tutor_v1_tutor_proto_rawDescGZIP(), []int{14}
}

func (x *PublishEventRequest) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *PublishEventRequest) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *PublishEventRequest) GetCorrect() bool {
	if x != nil {
		return x.Correct
	}
	return false
}

func (x *PublishEventRequest) GetResponseTimeMs() int32 {
	if x != nil {
		return x.ResponseTimeMs
	}
	return 0
}

func (x *PublishEventRequest) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *PublishEventRequest) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *PublishEventRequest) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

type PublishEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishEventResponse) Reset() {
	*x = PublishEventResponse{}
	mi := &file_tutor_v1_tutor_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishEventResponse) ProtoMessage() {}

func (x *PublishEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tutor_v1_tutor_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishEventResponse.ProtoReflect.Descriptor instead.
func (*PublishEventResponse) Descriptor() ([]byte, []int) {
	return file_tutor_v1_tutor_proto_rawDescGZIP(), []int{15}
}

func (x *PublishEventResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type ExplainErrorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Word          string                 `protobuf:"bytes,2,opt,name=word,proto3" json:"word,omitempty"`
	Expected      string                 `protobuf:"bytes,3,opt,name=expected,proto3" json:"expected,omitempty"`
	Got           string                 `protobuf:"bytes,4,opt,name=got,proto3" json:"got,omitempty"`
	Sentence      string                 `protobuf:"bytes,5,opt,name=sentence,proto3" json:"sentence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplainErrorRequest) Reset() {
	*x = ExplainErrorRequest{}
	mi := &file_tutor_v1_tutor_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainErrorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainErrorRequest) ProtoMessage() {}

func (x *ExplainErrorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tutor_v1_tutor_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainErrorRequest.ProtoReflect.Descriptor instead.
func (*ExplainErrorRequest) Descriptor() ([]byte, []int) {
	return file_tutor_v1_tutor_proto_rawDescGZIP(), []int{16}
}

func (x *ExplainErrorRequest) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *ExplainErrorRequest) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *ExplainErrorRequest) GetExpected() string {
	if x != nil {
		return x.Expected
	}
	return ""
}

func (x *ExplainErrorRequest) GetGot() string {
	if x != nil {
		return x.Got
	}
	return ""
}

func (x *ExplainErrorRequest) GetSentence() string {
	if x != nil {
		return x.Sentence
	}
	return ""
}

type ExplainErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Explanation   string                 `protobuf:"bytes,1,opt,name=explanation,proto3" json:"explanation,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"` // rag | llm
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplainErrorResponse) Reset() {
	*x = ExplainErrorResponse{}
	mi := &file_tutor_v1_tutor_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainErrorResponse) ProtoMessage() {}

func (x *ExplainErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tutor_v1_tutor_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainErrorResponse.ProtoReflect.Descriptor instead.
func (*ExplainErrorResponse) Descriptor() ([]byte, []int) {
	return file_tutor_v1_tutor_proto_rawDescGZIP(), []int{17}
}

func (x *ExplainErrorResponse) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *ExplainErrorResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type GetWeakTopicsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeakTopicsRequest) Reset() {
	*x = GetWeakTopicsRequest{}
	mi := &file_tutor_v1_tutor_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeakTopicsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeakTopicsRequest) ProtoMessage() {}

func (x *GetWeakTopicsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tutor_v1_tutor_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeakTopicsRequest.ProtoReflect.Descriptor instead.
func (*GetWeakTopicsRequest) Descriptor() ([]byte, []int) {
	return file_tutor_v1_tutor_proto_rawDescGZIP(), []int{18}
}

func (x *GetWeakTopicsRequest) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *GetWeakTopicsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type WeakTopic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          string                 `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	PKnow         float64                `protobuf:"fixed64,2,opt,name=p_know,json=pKnow,proto3" json:"p_know,omitempty"`
	Als           float64                `protobuf:"fixed64,3,opt,name=als,proto3" json:"als,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeakTopic) Reset() {
	*x = WeakTopic{}
	mi := &file_tutor_v1_tutor_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeakTopic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeakTopic) ProtoMessage() {}

func (x *WeakTopic) ProtoReflect() protoreflect.Message {
	mi := &file_tutor_v1_tutor_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeakTopic.ProtoReflect.Descriptor instead.
func (*WeakTopic) Descriptor() ([]byte, []int) {
	return file_tutor_v1_tutor_proto_rawDescGZIP(), []int{19}
}

func (x *WeakTopic) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *WeakTopic) GetPKnow() float64 {
	if x != nil {
		return x.PKnow
	}
	return 0
}

func (x *WeakTopic) GetAls() float64 {
	if x != nil {
		return x.Als
	}
	return 0
}

type GetWeakTopicsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []*WeakTopic           `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeakTopicsResponse) Reset() {
	*x = GetWeakTopicsResponse{}
	mi := &file_tutor_v1_tutor_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeakTopicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeakTopicsResponse) ProtoMessage() {}

func (x *GetWeakTopicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tutor_v1_tutor_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeakTopicsResponse.ProtoReflect.Descriptor instead.
func (*GetWeakTopicsResponse) Descriptor() ([]byte, []int) {
	return file_tutor_v1_tutor_proto_rawDescGZIP(), []int{20}
}

func (x *GetWeakTopicsResponse) GetTopics() []*WeakTopic {
	if x != nil {
		return x.Topics
	}
	return nil
}

var File_tutor_v1_tutor_proto protoreflect.FileDescriptor

const file_tutor_v1_tutor_proto_rawDesc = "" +
	"\n" +
	"\x14tutor/v1/tutor.proto\x12\btutor.v1\x1a\x1bgoogle/protobuf/empty.proto\"?\n" +
	"\vCredentials\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xa4\x01\n" +
	"\aSession\x127\n" +
	"\vcredentials\x18\x01 \x01(\v2\x15.tutor.v1.CredentialsR\vcredentials\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x17\n" +
	"\achat_id\x18\x03 \x01(\tR\x06chatId\x12(\n" +
	"\x10practice_chat_id\x18\x04 \x01(\tR\x0epracticeChatId\"\xb1\x01\n" +
	"\x14EnsureSessionRequest\x127\n" +
	"\vcredentials\x18\x01 \x01(\v2\x15.tutor.v1.CredentialsR\vcredentials\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x17\n" +
	"\achat_id\x18\x03 \x01(\tR\x06chatId\x12(\n" +
	"\x10practice_chat_id\x18\x04 \x01(\tR\x0epracticeChatId\"\xb8\x01\n" +
	"\x0eStatusResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tR\tprojectId\x12\x17\n" +
	"\achat_id\x18\x04 \x01(\tR\x06chatId\x12(\n" +
	"\x10practice_chat_id\x18\x05 \x01(\tR\x0epracticeChatId\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"\x80\x01\n" +
	"\vChatRequest\x12+\n" +
	"\asession\x18\x01 \x01(\v2\x11.tutor.v1.SessionR\asession\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\x11use_practice_chat\x18\x03 \x01(\bR\x0fusePracticeChat\"g\n" +
	"\tChatEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"j\n" +
	"\x0fPracticeRequest\x12+\n" +
	"\asession\x18\x01 \x01(\v2\x11.tutor.v1.SessionR\asession\x12\x14\n" +
	"\x05words\x18\x02 \x03(\tR\x05words\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\"\x8b\x01\n" +
	"\x10PracticeQuestion\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x18\n" +
	"\aoptions\x18\x02 \x03(\tR\aoptions\x12#\n" +
	"\rcorrect_index\x18\x03 \x01(\x05R\fcorrectIndex\x12 \n" +
	"\vexplanation\x18\x04 \x01(\tR\vexplanation\"\x85\x01\n" +
	"\x10PracticeResponse\x128\n" +
	"\tquestions\x18\x01 \x03(\v2\x1a.tutor.v1.PracticeQuestionR\tquestions\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x1f\n" +
	"\vrag_sources\x18\x03 \x03(\tR\n" +
	"ragSources\"\x98\x01\n" +
	"\x10RagSearchRequest\x12+\n" +
	"\asession\x18\x01 \x01(\v2\x11.tutor.v1.SessionR\asession\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12+\n" +
	"\x06corpus\x18\x03 \x01(\x0e2\x13.tutor.v1.RagCorpusR\x06corpus\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"`\n" +
	"\bRagChunk\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\asnippet\x18\x03 \x01(\tR\asnippet\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x02R\x05score\"Y\n" +
	"\x11RagSearchResponse\x12*\n" +
	"\x06chunks\x18\x01 \x03(\v2\x12.tutor.v1.RagChunkR\x06chunks\x12\x18\n" +
	"\acontext\x18\x02 \x01(\tR\acontext\"j\n" +
	"\x11EnrichWordRequest\x12+\n" +
	"\asession\x18\x01 \x01(\v2\x11.tutor.v1.SessionR\asession\x12\x12\n" +
	"\x04word\x18\x02 \x01(\tR\x04word\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\"\x8e\x01\n" +
	"\x12EnrichWordResponse\x12 \n" +
	"\vtranslation\x18\x01 \x01(\tR\vtranslation\x12\x18\n" +
	"\aexample\x18\x02 \x01(\tR\aexample\x12$\n" +
	"\rtranscription\x18\x03 \x01(\tR\rtranscription\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\"\xf3\x01\n" +
	"\x13PublishEventRequest\x12+\n" +
	"\asession\x18\x01 \x01(\v2\x11.tutor.v1.SessionR\asession\x12\x12\n" +
	"\x04word\x18\x02 \x01(\tR\x04word\x12\x18\n" +
	"\acorrect\x18\x03 \x01(\bR\acorrect\x12(\n" +
	"\x10response_time_ms\x18\x04 \x01(\x05R\x0eresponseTimeMs\x12\x1a\n" +
	"\battempts\x18\x05 \x01(\x05R\battempts\x12\x1b\n" +
	"\tcard_type\x18\x06 \x01(\tR\bcardType\x12\x1e\n" +
	"\n" +
	"difficulty\x18\a \x01(\tR\n" +
	"difficulty\"2\n" +
	"\x14PublishEventResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"\xa0\x01\n" +
	"\x13ExplainErrorRequest\x12+\n" +
	"\asession\x18\x01 \x01(\v2\x11.tutor.v1.SessionR\asession\x12\x12\n" +
	"\x04word\x18\x02 \x01(\tR\x04word\x12\x1a\n" +
	"\bexpected\x18\x03 \x01(\tR\bexpected\x12\x10\n" +
	"\x03got\x18\x04 \x01(\tR\x03got\x12\x1a\n" +
	"\bsentence\x18\x05 \x01(\tR\bsentence\"P\n" +
	"\x14ExplainErrorResponse\x12 \n" +
	"\vexplanation\x18\x01 \x01(\tR\vexplanation\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\"Y\n" +
	"\x14GetWeakTopicsRequest\x12+\n" +
	"\asession\x18\x01 \x01(\v2\x11.tutor.v1.SessionR\asession\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"H\n" +
	"\tWeakTopic\x12\x12\n" +
	"\x04word\x18\x01 \x01(\tR\x04word\x12\x15\n" +
	"\x06p_know\x18\x02 \x01(\x01R\x05pKnow\x12\x10\n" +
	"\x03als\x18\x03 \x01(\x01R\x03als\"D\n" +
	"\x15GetWeakTopicsResponse\x12+\n" +
	"\x06topics\x18\x01 \x03(\v2\x13.tutor.v1.WeakTopicR\x06topics*t\n" +
	"\tRagCorpus\x12\x1a\n" +
	"\x16RAG_CORPUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13RAG_CORPUS_EXERCISE\x10\x01\x12\x16\n" +
	"\x12RAG_CORPUS_EXAMPLE\x10\x02\x12\x1a\n" +
	"\x16RAG_CORPUS_EXPLANATION\x10\x032\x95\x05\n" +
	"\fTutorService\x12:\n" +
	"\x06Health\x12\x16.google.protobuf.Empty\x1a\x18.tutor.v1.StatusResponse\x12I\n" +
	"\rEnsureSession\x12\x1e.tutor.v1.EnsureSessionRequest\x1a\x18.tutor.v1.StatusResponse\x124\n" +
	"\x04Chat\x12\x15.tutor.v1.ChatRequest\x1a\x13.tutor.v1.ChatEvent0\x01\x12I\n" +
	"\x10GeneratePractice\x12\x19.tutor.v1.PracticeRequest\x1a\x1a.tutor.v1.PracticeResponse\x12D\n" +
	"\tSearchRag\x12\x1a.tutor.v1.RagSearchRequest\x1a\x1b.tutor.v1.RagSearchResponse\x12G\n" +
	"\n" +
	"EnrichWord\x12\x1b.tutor.v1.EnrichWordRequest\x1a\x1c.tutor.v1.EnrichWordResponse\x12M\n" +
	"\fPublishEvent\x12\x1d.tutor.v1.PublishEventRequest\x1a\x1e.tutor.v1.PublishEventResponse\x12M\n" +
	"\fExplainError\x12\x1d.tutor.v1.ExplainErrorRequest\x1a\x1e.tutor.v1.ExplainErrorResponse\x12P\n" +
	"\rGetWeakTopics\x12\x1e.tutor.v1.GetWeakTopicsRequest\x1a\x1f.tutor.v1.GetWeakTopicsResponseB\x1dZ\x1banki/internal/ai/pb;tutorpbb\x06proto3"

var (
	file_tutor_v1_tutor_proto_rawDescOnce sync.Once
	file_tutor_v1_tutor_proto_rawDescData []byte
)

func file_tutor_v1_tutor_proto_rawDescGZIP() []byte {
	file_tutor_v1_tutor_proto_rawDescOnce.Do(func() {
		file_tutor_v1_tutor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tutor_v1_tutor_proto_rawDesc), len(file_tutor_v1_tutor_proto_rawDesc)))
	})
	return file_tutor_v1_tutor_proto_rawDescData
}

var file_tutor_v1_tutor_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tutor_v1_tutor_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_tutor_v1_tutor_proto_goTypes = []any{
	(RagCorpus)(0),                // 0: tutor.v1.RagCorpus
	(*Credentials)(nil),           // 1: tutor.v1.Credentials
	(*Session)(nil),               // 2: tutor.v1.Session
	(*EnsureSessionRequest)(nil),  // 3: tutor.v1.EnsureSessionRequest
	(*StatusResponse)(nil),        // 4: tutor.v1.StatusResponse
	(*ChatRequest)(nil),           // 5: tutor.v1.ChatRequest
	(*ChatEvent)(nil),             // 6: tutor.v1.ChatEvent
	(*PracticeRequest)(nil),       // 7: tutor.v1.PracticeRequest
	(*PracticeQuestion)(nil),      // 8: tutor.v1.PracticeQuestion
	(*PracticeResponse)(nil),      // 9: tutor.v1.PracticeResponse
	(*RagSearchRequest)(nil),      // 10: tutor.v1.RagSearchRequest
	(*RagChunk)(nil),              // 11: tutor.v1.RagChunk
	(*RagSearchResponse)(nil),     // 12: tutor.v1.RagSearchResponse
	(*EnrichWordRequest)(nil),     // 13: tutor.v1.EnrichWordRequest
	(*EnrichWordResponse)(nil),    // 14: tutor.v1.EnrichWordResponse
	(*PublishEventRequest)(nil),   // 15: tutor.v1.PublishEventRequest
	(*PublishEventResponse)(nil),  // 16: tutor.v1.PublishEventResponse
	(*ExplainErrorRequest)(nil),   // 17: tutor.v1.ExplainErrorRequest
	(*ExplainErrorResponse)(nil),  // 18: tutor.v1.ExplainErrorResponse
	(*GetWeakTopicsRequest)(nil),  // 19: tutor.v1.GetWeakTopicsRequest
	(*WeakTopic)(nil),             // 20: tutor.v1.WeakTopic
	(*GetWeakTopicsResponse)(nil), // 21: tutor.v1.GetWeakTopicsResponse
	(*emptypb.Empty)(nil),         // 22: google.protobuf.Empty
}
var file_tutor_v1_tutor_proto_depIdxs = []int32{
	1,  // 0: tutor.v1.Session.credentials:type_name -> tutor.v1.Credentials
	1,  // 1: tutor.v1.EnsureSessionRequest.credentials:type_name -> tutor.v1.Credentials
	2,  // 2: tutor.v1.ChatRequest.session:type_name -> tutor.v1.Session
	2,  // 3: tutor.v1.PracticeRequest.session:type_name -> tutor.v1.Session
	8,  // 4: tutor.v1.PracticeResponse.questions:type_name -> tutor.v1.PracticeQuestion
	2,  // 5: tutor.v1.RagSearchRequest.session:type_name -> tutor.v1.Session
	0,  // 6: tutor.v1.RagSearchRequest.corpus:type_name -> tutor.v1.RagCorpus
	11, // 7: tutor.v1.RagSearchResponse.chunks:type_name -> tutor.v1.RagChunk
	2,  // 8: tutor.v1.EnrichWordRequest.session:type_name -> tutor.v1.Session
	2,  // 9: tutor.v1.PublishEventRequest.session:type_name -> tutor.v1.Session
	2,  // 10: tutor.v1.ExplainErrorRequest.session:type_name -> tutor.v1.Session
	2,  // 11: tutor.v1.GetWeakTopicsRequest.session:type_name -> tutor.v1.Session
	20, // 12: tutor.v1.GetWeakTopicsResponse.topics:type_name -> tutor.v1.WeakTopic
	22, // 13: tutor.v1.TutorService.Health:input_type -> google.protobuf.Empty
	3,  // 14: tutor.v1.TutorService.EnsureSession:input_type -> tutor.v1.EnsureSessionRequest
	5,  // 15: tutor.v1.TutorService.Chat:input_type -> tutor.v1.ChatRequest
	7,  // 16: tutor.v1.TutorService.GeneratePractice:input_type -> tutor.v1.PracticeRequest
	10, // 17: tutor.v1.TutorService.SearchRag:input_type -> tutor.v1.RagSearchRequest
	13, // 18: tutor.v1.TutorService.EnrichWord:input_type -> tutor.v1.EnrichWordRequest
	15, // 19: tutor.v1.TutorService.PublishEvent:input_type -> tutor.v1.PublishEventRequest
	17, // 20: tutor.v1.TutorService.ExplainError:input_type -> tutor.v1.ExplainErrorRequest
	19, // 21: tutor.v1.TutorService.GetWeakTopics:input_type -> tutor.v1.GetWeakTopicsRequest
	4,  // 22: tutor.v1.TutorService.Health:output_type -> tutor.v1.StatusResponse
	4,  // 23: tutor.v1.TutorService.EnsureSession:output_type -> tutor.v1.StatusResponse
	6,  // 24: tutor.v1.TutorService.Chat:output_type -> tutor.v1.ChatEvent
	9,  // 25: tutor.v1.TutorService.GeneratePractice:output_type -> tutor.v1.PracticeResponse
	12, // 26: tutor.v1.TutorService.SearchRag:output_type -> tutor.v1.RagSearchResponse
	14, // 27: tutor.v1.TutorService.EnrichWord:output_type -> tutor.v1.EnrichWordResponse
	16, // 28: tutor.v1.TutorService.PublishEvent:output_type -> tutor.v1.PublishEventResponse
	18, // 29: tutor.v1.TutorService.ExplainError:output_type -> tutor.v1.ExplainErrorResponse
	21, // 30: tutor.v1.TutorService.GetWeakTopics:output_type -> tutor.v1.GetWeakTopicsResponse
	22, // [22:31] is the sub-list for method output_type
	13, // [13:22] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_tutor_v1_tutor_proto_init() }
func file_tutor_v1_tutor_proto_init() {
	if File_tutor_v1_tutor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tutor_v1_tutor_proto_rawDesc), len(file_tutor_v1_tutor_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tutor_v1_tutor_proto_goTypes,
		DependencyIndexes: file_tutor_v1_tutor_proto_depIdxs,
		EnumInfos:         file_tutor_v1_tutor_proto_enumTypes,
		MessageInfos:      file_tutor_v1_tutor_proto_msgTypes,
	}.Build()
	File_tutor_v1_tutor_proto = out.File
	file_tutor_v1_tutor_proto_goTypes = nil
	file_tutor_v1_tutor_proto_depIdxs = nil
}
